### ISSUE TITLE
Updated config, needs pushing to live site

### ISSUE THREAD

**Issue by originalfoo** [DoESLiverpool/status#3]
Commit: https://github.com/DoESLiverpool/status/commit/60444fdc2433546c7ec9c21cf005d7d24584f68c

Because: https://github.com/DoESLiverpool/somebody-should/issues/490

**Comment by originalfoo** [comment]
Update - some further label name changes:

https://github.com/DoESLiverpool/status/commit/a0067008b36373795a44ba228e82afe32423e104

Also added the normal sized Ultimaker.

What is correct procedure for updating the files on the status server in future?

**Comment by skos-ninja** [comment]
Currently there isn't one but I'm going to look at setting automated deployments up so this will be easier in the future

**Comment by skos-ninja** [comment]
I have put this live again. Be warned that the config change you made pointed to the html page and not the json api.
